services:
  app_nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nodejs_app
    working_dir: /app
    volumes:
      - ./backend/nodejs:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: tail -f /dev/null
  app_angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    working_dir: /app
    volumes:
      - ./frontend/angular:/app
    ports:
      - "4200:4200"
    depends_on:
      - app_nodejs
    command: tail -f /dev/null
#    command: sleep infinity
  db:
    image: postgres:15
    container_name: base_datos_pg
    environment:
      POSTGRES_DB: db_developer
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: sys
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
