#FROM node:24 AS builder
FROM node:24-alpine AS builder
WORKDIR /app
COPY ./ /app/
#RUN npm ci
RUN npm install
RUN npm run build -- --configuration=production
FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
