services:
  db_posgresql:
    image: postgres:15
    container_name: datos_pg
    environment:
      POSTGRES_DB: db_developer
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: sys
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.nodejs.dev
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db_posgresql
  frontend:
    build:
      #context: ./frontend
      #dockerfile: ../Dockerfile.angular.dev
      dockerfile: ./Dockerfile.angular.dev
    container_name: frontend
    working_dir: /app
    volumes:
      #- ./frontend:/app
      - ./:/app
      - /app/node_modules
    ports:
      - "80:4300"
    depends_on:
      - backend
volumes:
  pgdata: